---
abstract: 'Pretty-print data structure as PHP serialization format'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Format-Pretty-PHPSerialization
requires:
  Exporter: 0
  PHP::Serialization: 0
  Test::More: 0.96
  perl: 5.010000
  strict: 0
  warnings: 0
resources:
  homepage: http://search.cpan.org/dist/Data-Format-Pretty-PHPSerialization/
  repository: http://github.com/sharyanto/perl-Data-Format-Pretty-PHPSerialization
version: 0.02
